using HandleDatabase;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.Win32;
using OfficeOpenXml;
using QC_Toray_App_v3.library;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace QC_Toray_App_v3
{
    /// <summary>
    /// Interaction logic for MainTable_UserControl.xaml
    /// </summary>
    public partial class MainTable_UserControl : System.Windows.Controls.UserControl
    {
        // Define an event for changing pages
        public event EventHandler<string> ChangePageRequested;
        public event EventHandler<string> UpdateLotAndGradeData;

        // Create DataTable
        DataTable dt = new DataTable();

        // Create DatabaseHandler
        DatabaseHandler databaseHandler = new DatabaseHandler(DatabaseConfig.ConnectionString);

        // Table Name
        private string LOT_OVERVIEW_TABLE = DatabaseConfig.LotOverviewTableName;

        public MainTable_UserControl()
        {
            InitializeComponent();
            tableGrid.AutoGeneratedColumns += DataGrid_AutoGeneratedColumns; // Attach event
            //LoadData();
            LoadDataFromDatabase();
        }

        // Test Selected event
        private void tableGrid_MouseDoubleClicked(object sender, MouseButtonEventArgs e)
        {
            if (tableGrid.SelectedItem is DataRowView rowView)
            {
                string lotValue = rowView["lot"].ToString();
                MessageBox.Show($"Selected Lot: {lotValue}");
            }
        }
        private void tableGrid_SelectionCellChanged(object sender, SelectedCellsChangedEventArgs e)
        {
            try
            {
                
                // Update Lot and Grade Data
                if (tableGrid.SelectedItem is DataRowView rowView)
                {
                    string formatLotGradeData = rowView["lot"].ToString() + "," + rowView["Grade"].ToString();
                    UpdateLotAndGradeData?.Invoke(this, formatLotGradeData);
                }

                GlobalState.Instance.IsFeatureEnabled = true;
                // Raise the event and pass the desired ListViewItem name
                ChangePageRequested?.Invoke(this, "LotOverview");

            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.ToString());
            }
        }

        private void LoadDataFromDatabase()
        {
            // Implement database loading logic here if needed
            dt = databaseHandler.GetTableDatabaseAsDataTable(LOT_OVERVIEW_TABLE);
            TrimDataTable(dt);

            // Bind to DataGrid
            tableGrid.ItemsSource = dt.DefaultView;
            ConfigureDataGrid();
        }

        private void TrimDataTable(DataTable dt)
        {
            foreach (DataRow row in dt.Rows)
            {
                foreach (DataColumn col in dt.Columns)
                {
                    if (row[col] is string strValue)
                    {
                        row[col] = strValue.Trim();
                    }
                }
            }
        }

        private void ConvertDateFormat(DataTable dt)
        {
            // If you need the column to be formatted as a string to explicitly remove the time,
            // you must change the column's data type, or add a new string column.

            // To format it as a string for display, use the previous function logic:
            foreach (DataRow row in dt.Rows)
            {
                // 1. Check if the value is a DateTime (as retrieved from SQL)
                if (row["Date"] is DateTime dateValue)
                {
                    // 2. Format the DateTime object as a string (e.g., "yy-MM-dd")
                    row["Date"] = dateValue.ToString("yy-MM-dd");
                }
                // Note: The DataGrid will now display this string.
            }

            DataRow[] rows = dt.Select();

            //MessageBox.Show($"Date column type: {dt.Columns["Date"].DataType}");
        }

        private void LoadData()
        {
            // Make RowFilter matching case-insensitive
            dt.CaseSensitive = false;

            // Sample Batch Numbers (These will be the headers)
            string[] Headers = { "Date", "Grade", "lot", "Order card no", "Sample from", "Pellet diameter", "Target sample", "Received sample", "Waiting sample", "Result of Current bt no", "Result of total quatity bt no", "Result Ng bt no"};

            //// Add batch columns as headers
            foreach (string header in Headers)
            {
                dt.Columns.Add(header);
            }

            //Generate Data
            List<string[]> rows = GenerateData();

            // Add rows to DataTable
            foreach (var row in rows)
            {
                dt.Rows.Add(row);
            }

            // Bind to DataGrid
            tableGrid.ItemsSource = dt.DefaultView;
            ConfigureDataGrid();
        }

        // Generate Example Data
        private List<string[]> GenerateData()
        {
            // Sample Data Rows (similar to the image)
            List<string[]> rows = new List<string[]>
            {
                new string[] { "08-09-25", "1101G-30", "1111111", "20250900112", "D", "Pass", "180", "16", "11,12,13","16", "6", "6,8,10" },
                new string[] { "09-09-25", "1101G-30", "22222222", "20250900112", "D", "Pass", "180", "34", "35,36,27","38", "6", "" },
                new string[] { "08-09-25", "1101G-30", "1111111", "-", "SIK", "Pass", "-", "1", "-","0", "1", "-" },
            };
            return rows;
        }

        private void ConfigureDataGrid()
        {
            // Set column width
            double standardColumnWidth = 120; // Width for all columns except column 0

            // Set Style Header
            var modernHeaderStyle = new Style(typeof(DataGridColumnHeader));
            modernHeaderStyle.Setters.Add(new Setter(BackgroundProperty, new SolidColorBrush(Color.FromRgb(250, 250, 250)))); // Light Gray
            modernHeaderStyle.Setters.Add(new Setter(HorizontalContentAlignmentProperty, HorizontalAlignment.Center));
            modernHeaderStyle.Setters.Add(new Setter(VerticalContentAlignmentProperty, VerticalAlignment.Center));

            // All other columns - Center aligned
            for (int i = 1; i < tableGrid.Columns.Count; i++)
            {
                // Set uniform column width
                tableGrid.Columns[i].Width = standardColumnWidth;

                tableGrid.Columns[i].CellStyle = new Style(typeof(DataGridCell))
                {
                    Setters = {
                                new Setter(HorizontalAlignmentProperty, HorizontalAlignment.Center),  // Center horizontal alignment
                                new Setter(VerticalAlignmentProperty, VerticalAlignment.Center),  // Center vertical alignment
                                new Setter(TextBlock.VerticalAlignmentProperty, VerticalAlignment.Center),  // Ensure text is centered
                                new Setter(TextBlock.HorizontalAlignmentProperty, HorizontalAlignment.Center),
                                new Setter(TextBlock.TextAlignmentProperty, TextAlignment.Center)
                    }
                };

                // Center align headers
                tableGrid.Columns[i].HeaderStyle = modernHeaderStyle;
            }

            
        }
        // define the event handler method:
        private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            ConfigureDataGrid(); // Ensure alignment after columns are generated
        }




        #region Button functions

        private void CheckLot_Clicked(object sender, RoutedEventArgs e)
        {
            //string lot = txbUser.Text;
            // Chenging for debuggin
            try
            {
                bool result = true; // VerifyLogin(user, pass);
                string display = result ? "Correct" : "Username or Password is failure";
                
                if (result)
                {
                    GlobalState.Instance.IsFeatureEnabled = true;
                    // Raise the event and pass the desired ListViewItem name
                    ChangePageRequested?.Invoke(this, "LotOverview"); // Example: Navigate to Operating page
                    //MessageBox.Show($"State: {GlobalState.Instance.IsFeatureEnabled}");
                }
                else { MessageBox.Show(display); }
                //MessageBox.Show($"State: {GlobalState.Instance.IsFeatureEnabled}");
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.ToString());
            }
        }

        // Export to CSV
        private void ExportToCSV_Click(object sender, RoutedEventArgs e)
        {
            SaveFileDialog saveFileDialog = new SaveFileDialog
            {
                Filter = "CSV file (*.csv)|*.csv",
                FileName = "table_data.csv"
            };

            if (saveFileDialog.ShowDialog() == true)
            {
                using (StreamWriter writer = new StreamWriter(saveFileDialog.FileName))
                {
                    foreach (DataColumn column in dt.Columns)
                    {
                        writer.Write(column.ColumnName + ",");
                    }
                    writer.WriteLine();

                    foreach (DataRow row in dt.Rows)
                    {
                        foreach (var item in row.ItemArray)
                        {
                            writer.Write(item.ToString() + ",");
                        }
                        writer.WriteLine();
                    }
                }
                MessageBox.Show("CSV Exported Successfully!");
            }
        }

        // Export to Excel
        private void ExportToExcel_Click(object sender, RoutedEventArgs e)
        {
            SaveFileDialog saveFileDialog = new SaveFileDialog
            {
                Filter = "Excel file (*.xlsx)|*.xlsx",
                FileName = "table_data.xlsx"
            };

            if (saveFileDialog.ShowDialog() == true)
            {
                ExcelPackage.LicenseContext = OfficeOpenXml.LicenseContext.NonCommercial;

                using (ExcelPackage package = new ExcelPackage())
                {
                    ExcelWorksheet worksheet = package.Workbook.Worksheets.Add("Table Data");

                    for (int col = 0; col < dt.Columns.Count; col++)
                    {
                        worksheet.Cells[1, col + 1].Value = dt.Columns[col].ColumnName;
                    }

                    for (int row = 0; row < dt.Rows.Count; row++)
                    {
                        for (int col = 0; col < dt.Columns.Count; col++)
                        {
                            worksheet.Cells[row + 2, col + 1].Value = dt.Rows[row][col];
                        }
                    }

                    package.SaveAs(new FileInfo(saveFileDialog.FileName));
                }
                MessageBox.Show("Excel Exported Successfully!");
            }
        }

        // Export to PDF
        private void ExportToPDF_Click(object sender, RoutedEventArgs e)
        {
            ExportDataGridToPDF(tableGrid); // Call it as an instance method
        }

        #endregion
        public void ExportDataGridToPDF(DataGrid dataGrid)
        {
            try
            {
                SaveFileDialog saveFileDialog = new SaveFileDialog
                {
                    Filter = "PDF Files (*.pdf)|*.pdf",
                    Title = "Save PDF File",
                    DefaultExt = "pdf"
                };

                if (saveFileDialog.ShowDialog() == true)
                {
                    string filePath = saveFileDialog.FileName;

                    // Create a PDF document with Landscape orientation
                    Document pdfDoc = new Document(PageSize.A4, 10, 10, 10, 10); // For portial just remove .Rotate() method
                    PdfWriter.GetInstance(pdfDoc, new FileStream(filePath, FileMode.Create));
                    pdfDoc.Open();

                    // Create a PDF table with the same number of columns as the DataGrid
                    PdfPTable pdfTable = new PdfPTable(dataGrid.Columns.Count);
                    pdfTable.WidthPercentage = 100;

                    // Create a BaseFont
                    //string fontPath = "D:\\Project\\QC_Toray\\QC_Toray_App_v3\\QC_Toray_App_v3\\Fonts\\segoeui.ttf"; // Change this path as needed
                    //BaseFont baseFont = BaseFont.CreateFont(fontPath, BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
                    BaseFont baseFont = BaseFont.CreateFont(BaseFont.HELVETICA, BaseFont.CP1252, BaseFont.NOT_EMBEDDED);
                    iTextSharp.text.Font font = new iTextSharp.text.Font(baseFont, 12); // Define font size

                    // Define column widths evenly
                    // Calculate column widths dynamically based on maximum text width in each column
                    float[] columnWidths = new float[dataGrid.Columns.Count];
                    float paddingFactor = 1.2f; // Add some extra space for padding

                    for (int colIndex = 0; colIndex < dataGrid.Columns.Count; colIndex++)
                    {
                        float maxColumnWidth = 0;

                        // Measure header width
                        string headerText = dataGrid.Columns[colIndex].Header.ToString();
                        maxColumnWidth = Math.Max(maxColumnWidth, baseFont.GetWidthPoint(headerText, font.Size));

                        // Measure data width for each row in the column
                        foreach (var item in dataGrid.Items)
                        {
                            if (item is DataRowView rowView)
                            {
                                string cellText = GetCellValue(rowView, dataGrid.Columns[colIndex]);
                                float textWidth = baseFont.GetWidthPoint(cellText, font.Size);
                                maxColumnWidth = Math.Max(maxColumnWidth, textWidth);
                            }
                        }

                        // Apply padding factor
                        columnWidths[colIndex] = maxColumnWidth * paddingFactor;
                    }

                    // Scale column widths to fit within page width
                    float totalTableWidth = columnWidths.Sum();
                    float maxPageWidth = PageSize.A4.Width - 40; // Account for margins (20 left + 20 right)

                    // If total width exceeds page width, scale down
                    if (totalTableWidth > maxPageWidth)
                    {
                        float scaleFactor = maxPageWidth / totalTableWidth;
                        for (int i = 0; i < columnWidths.Length; i++)
                        {
                            columnWidths[i] *= scaleFactor;
                        }
                    }

                    // Apply dynamic column widths
                    pdfTable.SetWidths(columnWidths);

                    // Add the headers from the DataGrid to the PDF table
                    foreach (var column in dataGrid.Columns)
                    {
                        PdfPCell cell = new PdfPCell(new Phrase(column.Header.ToString(), font))
                        {
                            BackgroundColor = BaseColor.LIGHT_GRAY
                        };
                        cell.HorizontalAlignment = Element.ALIGN_CENTER;
                        pdfTable.AddCell(cell);
                    }

                    // Add the rows from the DataGrid to the PDF table
                    foreach (var item in dataGrid.Items)
                    {
                        // Row Mangement
                        if (item is DataRowView rowView)
                        {
                            // Column Mangement
                            for (int colIndex = 0; colIndex < dataGrid.Columns.Count; colIndex++)
                            {
                                string cellValue = GetCellValue(rowView, dataGrid.Columns[colIndex]);
                                // Define Font to cell in this column
                                PdfPCell cell = new PdfPCell(new Phrase(cellValue, font));
                                // Text Alignment in cell
                                cell.HorizontalAlignment = Element.ALIGN_CENTER;
                                pdfTable.AddCell(cell);
                            }
                        }
                    }

                    // Add the table to the PDF document
                    pdfDoc.Add(pdfTable);
                    pdfDoc.Close();

                    MessageBox.Show($"PDF exported successfully to {filePath}", "Export Success", MessageBoxButton.OK, MessageBoxImage.Information);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Error exporting to PDF: {ex.Message}", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        // Helper function to extract cell value
        private string GetCellValue(DataRowView rowView, DataGridColumn column)
        {
            if (column is DataGridBoundColumn boundColumn && boundColumn.Binding is System.Windows.Data.Binding binding)
            {
                string columnName = binding.Path.Path;
                return rowView.Row[columnName]?.ToString() ?? string.Empty;
            }
            return string.Empty;
        }



        #region Filter Feature Area Function
        /// <summary>
        /// Filters the DataTable bound to tableGrid by the provided query string.
        /// Matches rows where 'lot' OR 'Grade' contains the query (case-insensitive).
        /// Call with empty or null to clear the filter.
        /// </summary>
        public void FilterTableBySearch(string query)
        {
            if (dt == null) return;

            if (string.IsNullOrWhiteSpace(query))
            {
                // Clear filter
                dt.DefaultView.RowFilter = string.Empty;
                return;
            }

            // Trim and escape single quotes for DataView RowFilter expression
            string q = query.Trim().Replace("'", "''");

            // Ensure case-insensitive matching (LoadData already sets CaseSensitive = false, but enforce here)
            dt.CaseSensitive = false;

            // Build row filter: use Convert(...) to ensure non-string columns are treated as strings
            // Search both 'lot' and 'Grade' columns for the query substring
            string filter = $"Convert([lot], 'System.String') LIKE '%{q}%' OR Convert([Grade], 'System.String') LIKE '%{q}%'";
            try
            {
                dt.DefaultView.RowFilter = filter;
            }
            catch (Exception ex)
            {
                // Fallback: clear filter on error
                dt.DefaultView.RowFilter = string.Empty;
                MessageBox.Show($"Filter error: {ex.Message}", "Filter Error", MessageBoxButton.OK, MessageBoxImage.Warning);
            }
        }

        // TextChanged handler for a TextBox named 'txbSearch'.
        // If txbSearch exists in XAML and is hooked, this will automatically filter as text changes.
        private void txbSearch_TextChanged(object sender, TextChangedEventArgs e)
        {
            var tb = sender as TextBox;
            FilterTableBySearch(tb?.Text ?? string.Empty);

            // Bind to DataGrid
            tableGrid.ItemsSource = dt.DefaultView;
            ConfigureDataGrid();
        }


        #endregion

      
    }
}
