//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QC_Toray_App_v3.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=192.168.0.123\\SQLEXPRESS; Database=camera_inspection; User Id=sa; Password" +
            "=1234;TrustServerCertificate=True;")]
        public string DatabaseConnectionString1 {
            get {
                return ((string)(this["DatabaseConnectionString1"]));
            }
            set {
                this["DatabaseConnectionString1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uv_lot_onprocess")]
        public string LotOverviewTableName {
            get {
                return ((string)(this["LotOverviewTableName"]));
            }
            set {
                this["LotOverviewTableName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.123")]
        public string ServerIp {
            get {
                return ((string)(this["ServerIp"]));
            }
            set {
                this["ServerIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7930")]
        public int ServerPort {
            get {
                return ((int)(this["ServerPort"]));
            }
            set {
                this["ServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=192.168.0.123\\SQLEXPRESS; Database=test_app_db; User Id=sa; Password=1234;" +
            "TrustServerCertificate=True;")]
        public string DatabaseConnectionString2 {
            get {
                return ((string)(this["DatabaseConnectionString2"]));
            }
            set {
                this["DatabaseConnectionString2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("usp_lot_add")]
        public string AddLotStoredProcedure {
            get {
                return ((string)(this["AddLotStoredProcedure"]));
            }
            set {
                this["AddLotStoredProcedure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tb_master_SamepleGroupName")]
        public string SampleGroupTable {
            get {
                return ((string)(this["SampleGroupTable"]));
            }
            set {
                this["SampleGroupTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tb_master_sample_limit")]
        public string MasterSampleLimitTable {
            get {
                return ((string)(this["MasterSampleLimitTable"]));
            }
            set {
                this["MasterSampleLimitTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tb_master_sample_item")]
        public string MasterSampleItemTable {
            get {
                return ((string)(this["MasterSampleItemTable"]));
            }
            set {
                this["MasterSampleItemTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("usp_UpdateOrInsertMasterSampleLimit")]
        public string UpdateOrInsertMasterSampleLimitProcedure {
            get {
                return ((string)(this["UpdateOrInsertMasterSampleLimitProcedure"]));
            }
            set {
                this["UpdateOrInsertMasterSampleLimitProcedure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tb_master_pattern")]
        public string MasterPatternTable {
            get {
                return ((string)(this["MasterPatternTable"]));
            }
            set {
                this["MasterPatternTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("usp_insert_or_update_master_pattern")]
        public string InserOrUpdateMasterPatternProcedure {
            get {
                return ((string)(this["InserOrUpdateMasterPatternProcedure"]));
            }
            set {
                this["InserOrUpdateMasterPatternProcedure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tb_master_grade_pattern")]
        public string MasterGradePatternTable {
            get {
                return ((string)(this["MasterGradePatternTable"]));
            }
            set {
                this["MasterGradePatternTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tb_master_daimeter")]
        public string MasterDiameterTable {
            get {
                return ((string)(this["MasterDiameterTable"]));
            }
            set {
                this["MasterDiameterTable"] = value;
            }
        }
    }
}
